#!/usr/bin/env python3
# This file is part of paslang.
# Copyright (C) 2026 Germán Luis Aracil Boned <garacil@tucall.com>
#
# paslang is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# paslang is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with paslang.  If not, see <https://www.gnu.org/licenses/>.

"""Constants at the edge of a width (1.0.147): every logic and additive
operator, and every comparison, of a narrow or wide integer with a
constant that has the top bit of its width set or sits at a limit, in
a register (a local), in memory (a global, in place), out of place, and
as a var parameter; modelled exactly and written as
testdata/immwide.paslang with its .out. The case that found the bug: a
UInt32 in a register and $FFFFEFFF, which no imm32 of andq reaches.

Run: python3 scripts/immmodel.py  (writes the two files)."""
import os

TYPES = [('Byte', 8, False), ('Word', 16, False), ('UInt32', 32, False),
         ('Int32', 32, True), ('Integer', 64, True)]

CONSTS = {
    'Byte': ['$EF', '$80', '$FF', '1'],
    'Word': ['$FFEF', '$8000', '$FFFF', '1'],
    'UInt32': ['$FFFFEFFF', '$80000000', '$FFFFFFFF', '$7FFFFFFF', '1'],
    'Int32': ['-4097', '-2147483648', '2147483647', '$7FFFEFFF', '1'],
    'Integer': ['$FFFFEFFF', '$80000000', '$FFFFFFFF', '$100000000', '-2147483649',
                '$7FFFFFFFFFFFFFFF', '-1'],
}
VALUES = {
    'Byte': ['0', '1', '$C8', '$FF'],
    'Word': ['0', '1', '$1C85', '$FFFF'],
    'UInt32': ['0', '1', '$1C85', '$80000001', '$FFFFFFFF'],
    'Int32': ['0', '1', '$1C85', '-2147483648', '-1'],
    'Integer': ['0', '1', '$1C85', '-2147483648', '$7FFFFFFFFFFFFFFF', '-1'],
}
OPS = ['and', 'or', 'xor', 'andnot', '+', '-']
CMPS = ['=', '<>', '<', '<=', '>', '>=']


def lit(s):
    if s.startswith('$'):
        return int(s[1:], 16)
    if s.startswith('-$'):
        return -int(s[2:], 16)
    return int(s)


def wrap(v, n, signed):
    v &= (1 << n) - 1
    if signed and v >> (n - 1):
        v -= 1 << n
    return v


def apply(op, x, k, n, signed):
    if op == 'and':
        r = x & k
    elif op == 'or':
        r = x | k
    elif op == 'xor':
        r = x ^ k
    elif op == 'andnot':
        r = x & ~k
    elif op == '+':
        r = x + k
    else:
        r = x - k
    return wrap(r, n, signed)


def cmp(op, x, k):
    return {'=': x == k, '<>': x != k, '<': x < k, '<=': x <= k, '>': x > k, '>=': x >= k}[op]


def main(tree):
    src = []
    out = []
    w = src.append
    w('program immwide;')
    w('')
    w('{ Generated by scripts/immmodel.py (1.0.147): every operator with a')
    w('  constant at the edge of its width, on a value in a register, in')
    w('  memory, out of place and through a var parameter. }')
    w('')
    w('var')
    for t, n, s in TYPES:
        w('  g%s: %s;' % (t, t))
    w('')
    for t, n, s in TYPES:
        w('procedure ByRef%s(var x: %s; k: Integer);' % (t, t))
        w('begin')
        w('  x := x xor %s(k);' % t if t != 'Integer' else '  x := x xor k;')
        w('end;')
        w('')
        w('procedure Test%s(v: %s);' % (t, t))
        w('var')
        w('  x, y: %s;' % t)
        w('  i: Integer;')
        w('begin')
        for k in CONSTS[t]:
            for op in OPS:
                # in place, in a register: a loop keeps x there
                w('  x := v;')
                w('  for i := 1 to 2 do')
                w('    x %s= %s;' % (op, k))
                w('  g%s := v;' % t)
                w('  g%s %s= %s;' % (t, op, k))
                w('  g%s %s= %s;' % (t, op, k))
                w('  y := v %s %s;' % (op, k))
                w("  WriteLn('%s ', v, ' %s %s: ', x, ' ', g%s, ' ', y);" % (t, op, k, t))
            w('  x := v;')
            w("  Write('%s ', v, ' cmp %s:');" % (t, k))
            for c in CMPS:
                w("  Write(' ', Ord(x %s %s));" % (c, k))
                w("  Write(Ord(v %s %s));" % (c, k))
            w('  WriteLn;')
        w('  x := v;')
        w('  ByRef%s(x, %s);' % (t, CONSTS[t][0]))
        w("  WriteLn('%s ', v, ' byref: ', x);" % t)
        w('end;')
        w('')
    w('begin')
    for t, n, s in TYPES:
        for v in VALUES[t]:
            w('  Test%s(%s);' % (t, v))
    w('end.')
    # the model
    for t, n, s in TYPES:
        for vs in VALUES[t]:
            v = wrap(lit(vs), n, s)
            for ks in CONSTS[t]:
                k = wrap(lit(ks), n, s)
                for op in OPS:
                    once = apply(op, v, k, n, s)
                    twice = apply(op, once, k, n, s)
                    out.append('%s %d %s %s: %d %d %d' % (t, v, op, ks, twice, twice, once))
                bits = ' '.join('%d%d' % (cmp(c, v, k), cmp(c, v, k)) for c in CMPS)
                out.append('%s %d cmp %s: %s' % (t, v, ks, bits))
            k0 = wrap(lit(CONSTS[t][0]), n, s)
            out.append('%s %d byref: %d' % (t, v, wrap(v ^ k0, n, s)))
    open(os.path.join(tree, 'testdata/immwide.paslang'), 'w').write('\n'.join(src) + '\n')
    open(os.path.join(tree, 'testdata/immwide.out'), 'w').write('\n'.join(out) + '\n')
    print('wrote testdata/immwide.paslang (%d lines) and .out (%d lines)' % (len(src), len(out)))


if __name__ == '__main__':
    import sys
    main(sys.argv[1] if len(sys.argv) > 1 else '.')
